name: Build and Push to AWS ECR

on: push

jobs:
  build-and-push:
    name: Build and Push Docker image to AWS ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: public.ecr.aws/g7x1p3h2/villahaven
          ECR_REPOSITORY: villahaven
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG server
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
